### ISSUE TITLE
No links to tiling scema in user guide section

### ISSUE THREAD

**Issue by rclelland** [DigitalGlobe/tiletanic#1]
Tiletanic (see here) or build your own. If you build your own, you’ll want to implement the public API of a tilescheme (see here) so that you can use the tile algorithms defined around this API.

(the "here"s don't link)

**Comment by youngpm** [comment]
Fixed!

http://tiletanic.readthedocs.org/en/latest/user_guide.html

I also added some example usage to the docs.
